-- JOIN TABLE 연습 - ON DELETE CASCADE로 자식 테이블 생성

--부모테이블인 SHOP 을 만들어보자 - 상품을 등록하는 테이블

CREATE TABLE SHOP (
    SANGCODE VARCHAR2(10) CONSTRAINT PK_SHOP_SANGCODE PRIMARY KEY,
    SANGNAME VARCHAR2(30),
    SANGPRICE NUMBER(7));
    
-- SHOP 의 상품코드를 참조해서 CART 에 담을수 있도록 테이블을 생성
--상품을 지우면 CART 의 데이타도 자동으로 지워지도록 ON DELETE CASCADE 를 설정해서 생성하자
CREATE TABLE CART (
    CARTNUM NUMBER(3) CONSTRAINT PK_CART_CARTNUM PRIMARY KEY,
    SANGCODE VARCHAR2(10),
    CNTNUM NUMBER(3) DEFAULT 1,
    CARTDAY DATE,
    CONSTRAINT FK_CART_SANGCODE FOREIGN KEY (SANGCODE) REFERENCES SHOP(SANGCODE) ON DELETE CASCADE);
    
--CART 에 들어갈 시퀀스 생성
CREATE SEQUENCE SEQCART NOCACHE;

--상품등록을 하자
INSERT INTO SHOP VALUES ('A100','체크블라우스',23000);
INSERT INTO SHOP VALUES ('A200','브이넥티셔츠',19000);
INSERT INTO SHOP VALUES ('A300','레이스블라우스',34000);
INSERT INTO SHOP VALUES ('A400','블랙진바지',56000);
INSERT INTO SHOP VALUES ('A500','실크스카프',12000);
INSERT INTO SHOP VALUES ('A600','인견자켓',59000);
INSERT INTO SHOP VALUES ('A700','롱오리털코트',123000);
INSERT INTO SHOP VALUES ('A800','체크티셔츠',35000);
INSERT INTO SHOP VALUES ('A900','실크블라우스',89000);

COMMIT; --커밋

SELECT * FROM SHOP; --확인

-- CART 에 원하는 상품을 담아보자
INSERT INTO CART (CARTNUM,SANGCODE,CARTDAY) VALUES (SEQCART.NEXTVAL,'A500',SYSDATE);
INSERT INTO CART (CARTNUM,SANGCODE,CARTDAY) VALUES (SEQCART.NEXTVAL,'A700',SYSDATE);
INSERT INTO CART (CARTNUM,SANGCODE,CNTNUM,CARTDAY) VALUES (SEQCART.NEXTVAL,'A800',3,SYSDATE);
INSERT INTO CART (CARTNUM,SANGCODE,CNTNUM,CARTDAY) VALUES (SEQCART.NEXTVAL,'A100',2,SYSDATE);
INSERT INTO CART (CARTNUM,SANGCODE,CNTNUM,CARTDAY) VALUES (SEQCART.NEXTVAL,'A500',1,SYSDATE);
INSERT INTO CART (CARTNUM,SANGCODE,CNTNUM,CARTDAY) VALUES (SEQCART.NEXTVAL,'A400',2,SYSDATE);

COMMIT; --커밋

SELECT * FROM CART;

--JOIN SQL 문을 이용해서 다음 순서로 출력해보세요.
--CARTNUM,SANGCODE,SANGNAME,SANGPRICE,CNTNUM,CARTDAY(YYYY-MM-DD HH;MM 이렇게 나오게)
SELECT 
    C.CARTNUM,S.SANGCODE,S.SANGNAME,S.SANGPRICE,C.CNTNUM,
    TO_CHAR(CARTDAY,'yyyy-mm-dd hh24:mi') CARTDAY
FROM SHOP S,CART C
WHERE S.SANGCODE=C.SANGCODE;

--OUTER JOIN 을 이용해서 아무도 카트에 담지 않은 상품을 알아보자
SELECT 
    C.CARTNUM,S.SANGCODE,S.SANGNAME,S.SANGPRICE,C.CNTNUM,
    TO_CHAR(CARTDAY,'yyyy-mm-dd hh24:mi') CARTDAY
FROM SHOP S,CART C
WHERE S.SANGCODE=C.SANGCODE(+) AND CARTNUM IS NULL;

--ON DELETE CASCADE 로 생성한경우 카트에 담긴 데이타도 부모테이블인 SHOP 에서 삭제가 가능하다.
-- 상품 삭제시 카트에 담긴 상품은 자동으로 삭제된다.

--SHOP 에서 A500을 제거해보자(카트에 두개가 담겨있음)
DELETE FROM SHOP WHERE SANGCODE='A500';

--다시 JOIN 으로 CART 확인하기
SELECT 
    C.CARTNUM,S.SANGCODE,S.SANGNAME,S.SANGPRICE,C.CNTNUM,
    TO_CHAR(CARTDAY,'yyyy-mm-dd hh24:mi') CARTDAY
FROM SHOP S,CART C
WHERE S.SANGCODE=C.SANGCODE;












